// Copyright 2023 The Gitea Authors. All rights reserved.
// SPDX-License-Identifier: MIT

package config

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
)

const registrationWarning = "This file is automatically generated by Gitea Runner. Do not edit it manually unless you know what you are doing. Removing this file will cause Gitea Runner to re-register as a new runner."

// Registration is the registration information for a runner
type Registration struct {
	Warning string `json:"WARNING"` // Warning message to display, it's always the registrationWarning constant

	ID        int64    `json:"id"`
	UUID      string   `json:"uuid"`
	Name      string   `json:"name"`
	Token     string   `json:"token"`
	Address   string   `json:"address"`
	Labels    []string `json:"labels"`
	Ephemeral bool     `json:"ephemeral"`
}

func LoadRegistration(file string) (*Registration, error) {
	info, err := os.Lstat(file)
	if err != nil {
		return nil, err
	}
	if !info.Mode().IsRegular() || info.Mode().Perm()&0o077 != 0 {
		return nil, &os.PathError{Op: "open insecure runner registration file", Path: file, Err: os.ErrPermission}
	}
	f, err := os.Open(file)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var reg Registration
	if err := json.NewDecoder(f).Decode(&reg); err != nil {
		return nil, err
	}

	reg.Warning = ""

	return &reg, nil
}

func SaveRegistration(file string, reg *Registration) error {
	if reg == nil {
		return errors.New("runner registration is nil")
	}
	if err := os.MkdirAll(filepath.Dir(file), 0o700); err != nil {
		return err
	}
	if info, err := os.Lstat(file); err == nil && !info.Mode().IsRegular() {
		return &os.PathError{Op: "replace insecure runner registration file", Path: file, Err: os.ErrPermission}
	} else if err != nil && !os.IsNotExist(err) {
		return err
	}
	temporary := file + ".new"
	if info, err := os.Lstat(temporary); err == nil {
		if !info.Mode().IsRegular() || info.Mode().Perm()&0o077 != 0 {
			return &os.PathError{Op: "replace insecure runner registration temporary file", Path: temporary, Err: os.ErrPermission}
		}
		if err := os.Remove(temporary); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	f, err := os.OpenFile(temporary, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return err
	}

	reg.Warning = registrationWarning

	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	if err = enc.Encode(reg); err == nil {
		err = f.Sync()
	}
	closeErr := f.Close()
	if err != nil {
		_ = os.Remove(temporary)
		return err
	}
	if closeErr != nil {
		_ = os.Remove(temporary)
		return closeErr
	}
	if err := os.Rename(temporary, file); err != nil {
		_ = os.Remove(temporary)
		return err
	}
	directory, err := os.Open(filepath.Dir(file))
	if err != nil {
		return err
	}
	err = directory.Sync()
	closeErr = directory.Close()
	if err != nil {
		return err
	}
	return closeErr
}
